find_path(Nanoid_INCLUDE_DIRS nanoid/nanoid.h)
find_library(Nanoid_LIBRARIES nanoid)

if (Nanoid_LIBRARIES AND Nanoid_INCLUDE_DIRS)
    set(Nanoid_FOUND YES)
    if (NOT Nanoid_FIND_QUIETLY)
        message(STATUS "Found nanoid: ${Nanoid_LIBRARIES}")
    endif ()
else ()
    if (Nanoid_FIND_REQUIRED)
        message(SEND_ERROR "Could NOT find nanoid")
    else ()
        if (NOT Nanoid_FIND_QUIETLY)
            message(STATUS "Could NOT find nanoid")
        endif ()
    endif ()
endif ()
